name: chapter_2 exercise_1 workflow

on:
    push:
        branches:
            - main

jobs:
    deploy-aws-lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'


            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            - name: package lambda function
              run: |
                cd chapter_2/exercise_1
                zip -r ../../function.zip hello.py
            - name: Deploy lambda function
              run: |
                  aws lambda update-function-code --function-name lambda-hello-world  --zip-file fileb://function.zip

            - name: Invoke lambda
              run: |
                  aws lambda invoke --function-name lambda-hello-world --payload '{}' output.json
                  cat output.json
